### ISSUE TITLE
PECL

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/cmark#1]
Can this go on PECL ?

/cc @remicollet

**Comment by krakjoe** [comment]
First revision of docs committed ...

**Comment by markhalliwell** [comment]
I know this is a separate project/API, but I think it would be beneficial to perhaps work with or add support for `thephpleague/commonmark`.

The `thephpleague/commonmark` API allows it to be easily extended. Something this doesn't seem to allow (yet). Thoughts?

X-ref: https://github.com/thephpleague/commonmark/issues/315

**Comment by krakjoe** [comment]
Some explaining ...

krakjoe/cmark provides an API for commonmark/cmark in PHP: It's not a standalone implementation but an API based  directly on, and linked too the exported commonmark/cmark API at compile time.

The reference implementation is missing facilities to customise the parser [1]

CustomInline and CustomBlock nodes can be used to facilitate custom nodes, and the API itself provides facilities to write custom render modes ... all of that is exposed to PHP.

krakjoe/cmark doesn't intend to do anything but expose the reference implementation (and it's obvious speed and efficiency) to PHP.

The league package has some focus on extensibility while this project does not. The only focus here is to expose the reference implementation to PHP, in the most efficient way possible: This means there is no tree of PHP objects: PHP objects are created just-in-time, cached, and then have their access optimised at runtime by the extension , while the underlying structure used by the reference implementation is not changed.

  [1](https://github.com/commonmark/cmark/pull/123 "attempted to add support for custom parser")

**Comment by markhalliwell** [comment]
> It's not a standalone implementation but an API based directly on

Sure. Sorry, when I made the other comment, it was before I realized who you were or the fact that this was going to be the "official" PHP extension.

It makes sense to have a straight port. Hope it becomes extendable soon. Would certainly help improve CommonMark's benchmarks: https://markdown.unicorn.fail/benchmarks

**Comment by krakjoe** [comment]
Just to be clear ... this is not the "official" PHP extension ...  there is no intention to merge this into core ...

**Comment by krakjoe** [comment]
@remicollet  I guess ready for PECL, is there anything you need me to do ?

**Comment by remicollet** [comment]
> @remicollet I guess ready for PECL, is there anything you need me to do ?

I just need to survive to the long build list  running for upcoming PHP release ;)

**Comment by remicollet** [comment]
@krakjoe I just run a few test builds against libcmark 0.28.3 (build statically to not rely on outdated official fedora packages), including running the test suite

- Fedora 25 to 28
- RHEL 6 and 7
- i386, x86_64, NTS; ZTS
- PHP 7.0, 7.1 and 7.2

Everything seems ok on my side

Please check package.xml, especially the **summary** and **description** (pasted from documentation)

Do you want to go directly for **1.0.0 as "stable"** or do you prefer some beta release first ?

**Comment by krakjoe** [comment]
yeah, go for stable ...

everything looks good ... thanks :)

Don't know if you want to create a release branch or whatever, shoot me a message with the process so I don't mess it up ...

**Comment by remicollet** [comment]
I will do the release tomorrow... already too much work for today ;)

**Comment by remicollet** [comment]
1.0.0 is now tagged and released on pecl, see https://pecl.php.net/package/cmark

@krakjoe the release branch is also created.

**Comment by krakjoe** [comment]
Very excellent stuff, thanks a bunch Remi :)

**Comment by markhalliwell** [comment]
Yes indeed! Thank you both!

Just an FYI, https://markdown.unicorn.fail now has this as part of its demo/benchmarks 😁
