### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/cmark#18]
- Fix #13 Reflection of CommonMark\CQL::__construct has no parameters
  - Fix #14 Reflection of CommonMark\Parse doesn't have return type
  - Fix #16 Reflection of CommonMark\Parser::finish doesn't have return type
  - Add PHP 7.4 support
  - Drop PHP 7.0 / 7.1 support

I think that's it ...

**Comment by remicollet** [comment]
@krakjoe build with 7.0 and 7.1 are broken, please confirm minimal is expected ? (only 7.2+)

P.S. a3d6bf0fac82b57c2ac86da4476d1c59f1cb73c9

**Comment by krakjoe** [comment]
That's correct, I've taken the opportunity to drop support for unsupported branches ...

**Comment by remicollet** [comment]
@krakjoe thanks for confirming, added to changelog, working of release now

**Comment by remicollet** [comment]
Travis is green,
Local QA builds are OK

Tagged and announced

**Comment by remicollet** [comment]
P.S. @krakjoe I also add the display of the extension version in phpinfo, seems useful for support to quickly get this information

**Comment by krakjoe** [comment]
Excellent, thanks again @remicollet :)
