### ISSUE TITLE
Appveyor

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/cmark#2]
Can we get an appveyor build going please ?

I have built on windows, but am so bad at av ...

/cc @weltling

**Comment by weltling** [comment]
I'll check it this night. Need to build the dep lib yet, too.

Targeting 7.0 and above, as usual?

Thanks.

**Comment by krakjoe** [comment]
Thanks :)

Yes, 7.0+ ...

**Comment by weltling** [comment]
@krakjoe could you enable AppVeyor please? I'm not sure I can do it for a particular project.

I've prepared the PECL build so far, the snapshot is running https://windows.php.net/downloads/pecl/snaps/cmark/20180325/

Thanks.

**Comment by krakjoe** [comment]
I've enabled AppVeyor and started the first build ... looks good ...

Excellent stuff, thanks :)

**Comment by weltling** [comment]
Oh, I've expected to have made some mistake :) Great then. I see we miss COPYING yet, for PECL. The PECL snap build is finished, the config seems fine. Local builds was fine, too. Looks like this ticket is done.

**Comment by krakjoe** [comment]
Agree, thanks for help ;)
