### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by remicollet** [krakjoe/cmark#3]
Despite travis is green, I have 2 failing tests

```
=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
CommonMark\Node\OrderedList [tests/Node/OrderedList/001.phpt]
CommonMark\Node\OrderedList isset start [tests/Node/OrderedList/009.phpt]
=====================================================================

$ cat tests/Node/OrderedList/001.diff
003+ int(1)
003- int(0)
006+ int(1)
006- int(0)
009+ int(1)
009- int(0)
012+ int(1)
012- int(0)

$ cat tests/Node/OrderedList/009.diff
001+ int(1)
002+ bool(true)
001- int(0)
002- bool(false)
```

@krakjoe can you have a look please ?

P.S. built with libcmark 0.27 (see [cmark](https://rpms.remirepo.net/rpmphp/zoom.php?rpm=cmark) for versions available in Fedora / RHEL / CentOS), perhaps a minimal version should be documented.

**Comment by krakjoe** [comment]
Yeah that's a change upstream, so the minimum required version should be set at 0.28.0 ....

What do you think is the best way to do that ?

**Comment by krakjoe** [comment]
@remicollet going to assign this to you: can you please impose that requirement in the best way you know how, I just noticed the pkgconfig stuff, I'm totally unfamiliar with that ...

**Comment by remicollet** [comment]
@krakjoe easy, see 912a5f2ea1009be014609c760b2a986de011e6fa

BTW, this mean I will only be able to provide package for Fedora 28+ (nothing for Fedora < 28 and RHEL / CentOS) ... :(

**Comment by remicollet** [comment]
but condition missing for build without pkg-config

**Comment by remicollet** [comment]
@krakjoe please check new config.m4

**Comment by krakjoe** [comment]
LGTM, ta :)
