### ISSUE TITLE
Release please

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/cmark#7]
Hi Remi,

Can you do a release of develop branch please ?

I have a feature branch waiting to be merged, and I'll merge into develop after release, and then work on coverage and tests and it will be included in the next release ...

**Comment by remicollet** [comment]
Can you paste the changelog information ?

From a quick look to git commit, I only see "visitation improvements " (but perhaps some details will be welcome by users)

**Comment by krakjoe** [comment]
* improve efficiency of visitation, only looking up functions one time for each accept()
  * allow returning [Event => Node] from enter/leave, providing full control over backing iterator

That's all that's waiting there ...

Thanks ;)

**Comment by remicollet** [comment]
Ty.

I will take care of the release later today, or tomorrow early.

**Comment by krakjoe** [comment]
Thanks muchly

**Comment by remicollet** [comment]
Version 1.0.1 is tagged and  released on PECL
