### ISSUE TITLE
Upcoming release

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/cmark#8]
Given that the new release will have some bug fixes, and a new feature, but retains bc, are we calling that 1.1.0 ?

Writing docs and need to put versions numbers of new functions in, release will be maybe next Monday, when docs are finished ...

**Comment by remicollet** [comment]
Indeed, new feature imply bumping second digit (semver), so 1.1

**Comment by krakjoe** [comment]
Okay cool, I'll let you bump the versions when you do the release ... I have just committed the first revision of docs for changes and will probably spend a while editing them ...

I guess we can have the release tomorrow afternoon/evening, if that suits you ?

**Comment by krakjoe** [comment]
@weltling  any idea why appveyor isn't running ? should the file name be prefixed with a dot ?

**Comment by remicollet** [comment]
@krakjoe can you paste here information for changelog ?
and I can take care of the release process tomorrow, by end of afternoon, if ready on your side

Only this, right ?
* Add CQL, CommonMark Query Language: allow the programmer to navigate the document without loading entire trees or intermediate objects into memory

**Comment by krakjoe** [comment]
That, and some refcounting fixes, which can just be logged as "refcounting fixes" in changelog ...

Thanks :)

**Comment by krakjoe** [comment]
Just to note, release needs to be made from a02bc8268f743fb1f21f242c1eb50fd98d76d5aa ... Ta :)

**Comment by remicollet** [comment]
@krakjoe `cql_ast_loop_begin`_in and `cql_ast_loop_next_in` are missing the return (after the switch), this raise new build warnings [-Wreturn-type]. Shouldn't this functions return `CQLI_NOP` ?

**Comment by krakjoe** [comment]
Sorry about that, fixed ... there was a strange error on travis earlier, complaining about a missing symbol that every other build found, did you have any error like that locally ?

**Comment by remicollet** [comment]
Looks like this is a erratic failure.
Travis use an old re2c (0.13.5)

     re2c: error: line 59, column 37: unrecognized configuration name 'define:YYSETCONDITION:naked' or illegal integer value

The file is saved in git, generated by re2c .0.16 and seems ok.

Test build are running, only a failure with old gcc, I'm investigating on it.

**Comment by remicollet** [comment]
```
# make
/bin/sh /builddir/build/BUILD/php-pecl-cmark-1.1.0/NTS/libtool --mode=compile cc  -I. -I/builddir/build/BUILD/php-pecl-cmark-1.1.0/NTS -DPHP_ATOM_INC -I/builddir/build/BUILD/php-pecl-cmark-1.1.0/NTS/include -I/builddir/build/BUILD/php-pecl-cmark-1.1.0/NTS/main -I/builddir/build/BUILD/php-pecl-cmark-1.1.0/NTS -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic   -c /builddir/build/BUILD/php-pecl-cmark-1.1.0/NTS/src/cql_parser.c -o src/cql_parser.lo 
libtool: compile:  cc -I. -I/builddir/build/BUILD/php-pecl-cmark-1.1.0/NTS -DPHP_ATOM_INC -I/builddir/build/BUILD/php-pecl-cmark-1.1.0/NTS/include -I/builddir/build/BUILD/php-pecl-cmark-1.1.0/NTS/main -I/builddir/build/BUILD/php-pecl-cmark-1.1.0/NTS -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c /builddir/build/BUILD/php-pecl-cmark-1.1.0/NTS/src/cql_parser.c  -fPIC -DPIC -o src/.libs/cql_parser.o
In file included from /opt/src/php-cmark/src/cql_parser.y:8:
./src/cql_lexer.h:23: error: redefinition of typedef 'cql_lex_t'
/opt/src/php-cmark/src/cql_parser.y:32: note: previous declaration of 'cql_lex_t' was here

```
Any idea welcome ;)

**Comment by remicollet** [comment]
@krakjoe please review f02918a13343a60a9c00e517c558ff3ee7813640

If everything ok, I will do the release

**Comment by remicollet** [comment]
Travis seems ok (only nightly is failing, but for a while)

Local build + tests ok, with Fedora 25-28, RHEL 6-7, i386, x86_64, NTS, ZTS, PHP 7.0, 7.1, 7.2

@krakjoe waiting for your "GO"

**Comment by krakjoe** [comment]
go

**Comment by remicollet** [comment]
Version 1.1.0 is tagged and released on https://pecl.php.net/package/cmark
