### ISSUE TITLE
pkgconfig libjit

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/cmark#9]
Hi remi, can you do the pkgconfig magic for libjit in feature/jit branch please ?

**Comment by remicollet** [comment]
I will have a look next-week (will be offline in a few minutes)

Link to the libjit project ?  (I don't see anything in RPM repository, GNU libjit seems outdated and discouraged, and http://git.savannah.gnu.org/cgit/libjit.git doesn't seems to have any stable release)

**Comment by krakjoe** [comment]
Yeah they don't have a stable release, but it's widely used stuff ... that's the correct repo ... Thanks ...

**Comment by remicollet** [comment]
> but it's widely used stuff

Hmm... really... ?
this library is not in Fedora nor in Debian, so not used by the >20k projects available in these distro...

**Comment by krakjoe** [comment]
Well ... apparently not then ... do you know of any projects that use a jit, do they use llvm ? I hate llvm, it's super over complicated ...

**Comment by remicollet** [comment]
> do you know of any projects that use a jit ?

libpcre / libpcre2 ?


P.S. the libpcre jit implementation is unusable for now on some secure distributions (e.g with SELinux) as it does some very bad things with memory

**Comment by krakjoe** [comment]
Any idea what https://travis-ci.org/krakjoe/cmark/jobs/369993149#L725 is about ?

**Comment by remicollet** [comment]
Perhaps pkg-config not installed by default ?
Else you have to use --with-pkgconfigdir for non standard installation dir.

**Comment by krakjoe** [comment]
Closing, don't plan to work on that branch anymore ...
